### ISSUE TITLE
Lista de tiles do release 2.0

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.tiles#220]
O propósito desta issue é simplesmente servir de referência no trabalho de migração de tiles dos portais Brasil e Planalto para o IDG baunilha:

- [x] citação (#219)
- [x] navegação (#225)
- [x] galeria (#224)
- [x] carrossel de grupo (#235)
- [x] galeria de fotos (#223)
- [x] foto do dia (#222)
- [x] carrosel de videos (#228)

**Comment by hvelarde** [comment]
@idgserpro o tile de destaques não está previsto no IDG v2 e será removido; ao remover o overrides do tile de lista também vamos evitar problemas ai.
